# Raja Jain
## Asignment 2 - Rules Based Classification
### **Goal:** The goal of this assignment is to give you the opportunity to develop an intuition for classification using rule-based classification.

The data is to be used to predict whether individuals will cheat in filing their taxes or not. The attributes are refund, indicating whether an individual received tax refund or not, marital_status indicating whether the individual is married, single, or divorced, the income_above_80k, indicating whether an individual’s taxable income is above $80,000 or not. The output variable, cheat, is a binary variable indicating whether an individual cheated in filing taxes or not.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk
from sklearn.preprocessing import LabelEncoder

In [2]:
tax_data = """refund	marital_status	income_above_80k	cheat
1	yes	single	yes	no
2	no	married	yes	no
3	no	single	no	no
4	yes	married	yes	no
5	no	divorced	yes	yes
6	no	married	no	no
7	yes	divorced	yes	no
8	no	single	yes	yes
9	no	married	no	no
10	no	single	yes	yes"""

# convert tax_data to a table
def str_to_data(data_str: str):
    dat = data_str.split("\n")
    dat = [row.split("\t") for row in dat]
    dat[0].insert(0, "index")
    dat = pd.DataFrame(dat[1:], columns=dat[0]).set_index(["index"])
    return dat


tax_data = str_to_data(tax_data)
tax_data

      refund marital_status income_above_80k cheat
index
1        yes         single              yes    no
2         no        married              yes    no
3         no         single               no    no
4        yes        married              yes    no
5         no       divorced              yes   yes
6         no        married               no    no
7        yes       divorced              yes    no
8         no         single              yes   yes
9         no        married               no    no
10        no         single              yes   yes

a)	Write an IF-THEN rule derived from this decision tree, that can be used to classify instances in the data suppose your desire is to predict “yes” for the output variable.

In [3]:
# IF-THEN rules for classification

cheat = 0
if "refund" == "no":
    if "income_above_80k" == "yes":
        if "marital_status" == "single" or "marital_status" == "divorced":
            cheat = 1

b)	In code, create a function with an if-else statement to implement the rule you wrote above in question 1a. You can name the function predict. The function takes the input data and returns a vector of predicted output values. You can decide if you want your function’s input data argument to be a numpy array or a data frame, ,then structure your function body to process the input data accordingly. Provide some brief document of your function. You can loop through each instance in the input data and assess whether the instance satisfies the rule for predicting “yes” or not. If the instance satisfies the rule for predicting “yes”, then predict 1, otherwise, predict 0.

In [4]:
# build a decision tree to predict "cheat" from the tax_data
def predict(X):
    """takes a vector X, and implements if then logic to predict whether someone will cheat on their taxes or not"""
    cheat = 0
    if X["refund"] == "no":
        if X["income_above_80k"] == "yes":
            if X["marital_status"] == "single" or X["marital_status"] == "divorced":
                cheat = 1
    return cheat


predictions = []
for _, row in tax_data.iterrows():
    print(row.to_dict())
    prediction = predict(row)
    predictions.append(prediction)
    print("Prediction:", prediction)

print("All predictions:", predictions)

{'refund': 'yes', 'marital_status': 'single', 'income_above_80k': 'yes', 'cheat': 'no'}
Prediction: 0
{'refund': 'no', 'marital_status': 'married', 'income_above_80k': 'yes', 'cheat': 'no'}
Prediction: 0
{'refund': 'no', 'marital_status': 'single', 'income_above_80k': 'no', 'cheat': 'no'}
Prediction: 0
{'refund': 'yes', 'marital_status': 'married', 'income_above_80k': 'yes', 'cheat': 'no'}
Prediction: 0
{'refund': 'no', 'marital_status': 'divorced', 'income_above_80k': 'yes', 'cheat': 'yes'}
Prediction: 1
{'refund': 'no', 'marital_status': 'married', 'income_above_80k': 'no', 'cheat': 'no'}
Prediction: 0
{'refund': 'yes', 'marital_status': 'divorced', 'income_above_80k': 'yes', 'cheat': 'no'}
Prediction: 0
{'refund': 'no', 'marital_status': 'single', 'income_above_80k': 'yes', 'cheat': 'yes'}
Prediction: 1
{'refund': 'no', 'marital_status': 'married', 'income_above_80k': 'no', 'cheat': 'no'}
Prediction: 0
{'refund': 'no', 'marital_status': 'single', 'income_above_80k': 'yes', 'cheat': 'yes'}
Prediction: 1
All predictions: [0, 0, 0, 0, 1, 0, 0, 1, 0, 1]

c)	Create another function that implements the rule for predicting “yes” for the output, but this time, you will not use if-else statement or a loop. Rather use numpy arrays, matrices or vector to vectorize your code for faster and more efficient implementation. If the instance satisfies the rule for predicting “yes”, then predict 1, otherwise, predict 0. You can use logical operators for such implementation to compare values of test instances to values of attributes in the rule. This function still takes the input data and returns a vector of predicted values. You can call this function vectorized_predict.

In [5]:
le_tax_data = tax_data[["refund", "marital_status", "income_above_80k"]].apply(
    LabelEncoder().fit_transform
)


def vectorized_predict(X):
    """takes a vector X, and implements if then logic to predict whether someone will cheat on their taxes or not"""
    cheat = 0
    if X[0] == 0:
        if X[2] == 1:
            if X[1] != 1:
                cheat = 1
    return cheat


display(le_tax_data)

vectorized_predictions = np.apply_along_axis(vectorized_predict, 1, le_tax_data.values)
vectorized_predictions

       refund  marital_status  income_above_80k
index
1           1               2                 1
2           0               1                 1
3           0               2                 0
4           1               1                 1
5           0               0                 1
6           0               1                 0
7           1               0                 1
8           0               2                 1
9           0               1                 0
10          0               2                 1

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1])

d)	Select the input data (refund, marital_status, income_above_80k) in the training data and apply your predict function to the input data to predict the outcome values of the input data. Your function should return a vector of predicted values. 
Paste your code an output here

In [6]:
tax_data[["refund", "marital_status", "income_above_80k"]].apply(predict, axis=1)

index
1     0
2     0
3     0
4     0
5     1
6     0
7     0
8     1
9     0
10    1
dtype: int64



e)	Select the input data (refund, marital_status, income_above_80k) in the training data and apply your vectorized_predict function to the input data to predict the outcome values of the input data. Your function should return a vector of predicted values. Are the predicted values with the vectorized_predict function the same as the predicted values obtained through the predict function? (you should have the same results).

In [7]:
tax_data.apply(predict, axis=1) == le_tax_data.apply(vectorized_predict, axis=1)

index
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
dtype: bool

f)	Include the predicted values as a column to the training data and name that column predicted_cheat.

In [8]:
tax_data["predicted_cheat"] = tax_data.apply(predict, axis=1)

tax_data

      refund marital_status income_above_80k cheat  predicted_cheat
index
1        yes         single              yes    no                0
2         no        married              yes    no                0
3         no         single               no    no                0
4        yes        married              yes    no                0
5         no       divorced              yes   yes                1
6         no        married               no    no                0
7        yes       divorced              yes    no                0
8         no         single              yes   yes                1
9         no        married               no    no                0
10        no         single              yes   yes                1

g)	Create a function that computes the overall accuracy of the classification. You can call this function overall_accuracy. The function should take two arguments, a vector of  actual output values and a vector of predicted output values, then returns the classification accuracy. Inside the function, you can use boolean logic to compare the actual and predicted values, then count the proportion of how many predicted values are equal to the actual values to get the overall accuracy.

In [9]:
# Create a function that computes the overall accuracy of the classification. You can call this function overall_accuracy. The function should take two arguments, a vector of  actual output values and a vector of predicted output values, then returns the classification accuracy. Inside the function, you can use boolean logic to compare the actual and predicted values, then count the proportion of how many predicted values are equal to the actual values to get the overall accuracy.


def create_confusion_matrix(actual: np.ndarray, predicted: np.ndarray):
    """
    Computes the overall accuracy of the classification.
    """
    tn = 0
    fp = 0
    fn = 0
    tp = 0
    total = 0

    for a, p in zip(actual, predicted):
        total += 1
        if a == 0 and p == 0:
            tn += 1
        elif a == 0 and p == 1:
            fp += 1
        elif a == 1 and p == 0:
            fn += 1
        elif a == 1 and p == 1:
            tp += 1

    return [[tn, fp], [fn, tp]], total


def overall_accuracy(confusion_matrix: np.ndarray):
    tn, fp, fn, tp = (
        confusion_matrix[0][0],
        confusion_matrix[0][1],
        confusion_matrix[1][0],
        confusion_matrix[1][1],
    )
    return (tn + tp) / (tn + fp + fn + tp)


confusion_matrix, _ = create_confusion_matrix(
    actual=tax_data["cheat"].replace({"no": 0, "yes": 1}).values,
    predicted=tax_data["predicted_cheat"].values,
)

overall_accuracy(confusion_matrix)

1.0

h)	Create a confusion matrix using the predicted and actual output values. You can use pandas crosstab function.

In [10]:
confusion_matrix

[[7, 0], [0, 3]]

i)	Supose the test set data is as follows. 
	refund	marital_status	income_above_80k	cheat
1	no	single	yes	no
2	no	single	yes	no
3	no	married	yes	no
4	no	divorced	no	no
5	no	married	yes	no
6	no	single	yes	no
7	yes	single	yes	no
8	no	single	yes	yes
9	yes	married	yes	yes
10	yes	single	no	yes

Apply the vectorized_predict function to the input of the test dataset to predict the output values for the test dataset. Include these predicted values as a column to the test dataset and called this column predicted_cheat.

In [11]:
test_data = """refund	marital_status	income_above_80k	cheat
1	no	single	yes	no
2	no	single	yes	no
3	no	married	yes	no
4	no	divorced	no	no
5	no	married	yes	no
6	no	single	yes	no
7	yes	single	yes	no
8	no	single	yes	yes
9	yes	married	yes	yes
10	yes	single	no	yes"""

# Apply the vectorized_predict function to the input of the test dataset to predict the output values for the test dataset. Include these predicted values as a column to the test dataset and called this column predicted_cheat.
test_data = str_to_data(test_data)

display(test_data)

le_test_data = test_data[["refund", "marital_status", "income_above_80k"]].apply(
    LabelEncoder().fit_transform
)

test_data["predicted_cheat"] = le_test_data.apply(vectorized_predict, axis=1)

display(test_data)

      refund marital_status income_above_80k cheat
index
1         no         single              yes    no
2         no         single              yes    no
3         no        married              yes    no
4         no       divorced               no    no
5         no        married              yes    no
6         no         single              yes    no
7        yes         single              yes    no
8         no         single              yes   yes
9        yes        married              yes   yes
10       yes         single               no   yes

      refund marital_status income_above_80k cheat  predicted_cheat
index
1         no         single              yes    no                1
2         no         single              yes    no                1
3         no        married              yes    no                0
4         no       divorced               no    no                0
5         no        married              yes    no                0
6         no         single              yes    no                1
7        yes         single              yes    no                0
8         no         single              yes   yes                1
9        yes        married              yes   yes                0
10       yes         single               no   yes                0

j)	Apply the overall_accuracy function to the predicted out values and actual output values of the test set to compute the overall accuracy. Compare the overall accuracy of the test set and that of the training set. Is there overfitting? Why or why not? If there is overfitting, what would you do to avoid overfitting the rule to the training set?

In [13]:
# j)	Apply the overall_accuracy function to the predicted out values and actual output values of the test set to compute the overall accuracy. Compare the overall accuracy of the test set and that of the training set. Is there overfitting? Why or why not? If there is overfitting, what would you do to avoid overfitting the rule to the training set?

test_data_confusion_matrix, _ = create_confusion_matrix(
    actual=test_data["cheat"].replace({"no": 0, "yes": 1}).values,
    predicted=test_data["predicted_cheat"].values,
)

overall_accuracy(test_data_confusion_matrix)

0.5

# Question 2 

You will use the same training dataset provided in question 1. Suppose we wanted to create one rule using only one attribute that best classifies the input data, you will need to write a function or an algorithm to find that best attribute. There are different approaches we can use to evaluate the best attritubute that will classify our data with the highest accuracy. One of the accuracy measures we can use to find the best attribute is information gain, which uses entropy.

a) Given the training dataset in question 1, write a function that computes the entropy of output variable. The function should take the entire training dataset, and the name of the output variable as arguments and return the entropy value. You can call the function, entropy. 
Note that entropy H(S) of the target variable T with possible values C_i for a set of S examples is given by:
H(S) = - ∑_(i=1)^c▒p_i   log_2⁡〖p_i 〗 
where p_i  is proportion of class c_i  in the S examples 

Alternatively, you could also define entropy for a binary target variable as:
 
Where p = proportion of the desired class or proportion of “yes” in the given data. 

Apply the entropy function to the training dataset to compute the entropy. Do you think the data is more pure, less pure or more/less pure?

In [ ]:
# a) Given the training dataset in question 1, write a function that computes the entropy of output variable. The function should take the entire training dataset, and the name of the output variable as arguments and return the entropy value. You can call the function, entropy.

# Note that entropy H(S) of the target variable T with possible values C_i for a set of S examples is given by:
# H(S) = - ∑_(i=1)^c▒p_i   log_2⁡〖p_i 〗
# where p_i  is proportion of class c_i  in the S examples

# Alternatively, you could also define entropy for a binary target variable as:

# Where p = proportion of the desired class or proportion of “yes” in the given data.

# Apply the entropy function to the training dataset to compute the entropy. Do you think the data is more pure, less pure or more/less pure?


def entropy(p: float):
    """p = proportion of the desired class or proportion of “yes” in the given data"""
    return -p * np.log2(p) - (1 - p) * np.log2(1 - p)